### ISSUE TITLE
add display:block for img tags

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/classic#14]
<a> tegi ichida berilayotgan image'lar uchun display:block berib ketilsa, maqsadga muvofiq bo'ladi.
https://github.com/ShokhrukhTurgunov/classic/blob/04983d4b61d68d48fc906777e2d346209459ad1f/index.html#L30

**Comment by ShokhrukhTurgunov** [comment]
ha, esdan chiqibti. To'g'rilaymiz
