### ISSUE TITLE
add white-space: nowrap for non wrapping texts

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/classic#15]
navbar va footerdagi textlarni yaqinlashtirganda yozuvlar keyingi qatorga tushib ketyapdi. shuning uchun white-space: nowrap; berib qoyganingiz maqul
https://github.com/ShokhrukhTurgunov/classic/blob/04983d4b61d68d48fc906777e2d346209459ad1f/css/main.css#L81

**Comment by ShokhrukhTurgunov** [comment]
rahmat, shunday qilamiz
