### ISSUE TITLE
remove href from main page logo

### ISSUE THREAD

**Issue by vayvoo** [ShokhrukhTurgunov/classic#16]
Bosh sahifada turganligimiz uchun logotipdagi <a> tegining href yozuvini o'chirib yuborsak ham bo'ladi
https://github.com/ShokhrukhTurgunov/classic/blob/04983d4b61d68d48fc906777e2d346209459ad1f/index.html#L29

**Comment by ShokhrukhTurgunov** [comment]
bajarildi
