### ISSUE TITLE
All background images

### ISSUE THREAD

**Issue by OzodaKhamdamova** [ShokhrukhTurgunov/classic#3]
https://github.com/ShokhrukhTurgunov/classic/blob/4117ea98bc43dd4a482b766d39f0aea50a3e8fc7/css/main.css#L151

Hamma background image lar "" (qo'shtirnoq) orasiga olib yozilishi Best practice bo'lardi

**Comment by ShokhrukhTurgunov** [comment]
Raxmat. Shunga harakat qilaman
