### ISSUE TITLE
Popular dishes position

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/classic#4]
![image](https://user-images.githubusercontent.com/79502241/116643311-3aae1400-a98a-11eb-88ed-de9b6daf4c12.png)
pizzalar ro'yhati maket bo'yicha markazda joylashmagan. Maketga solishtirilsa o'zgartirilishi kerak lekin bir qaraganda markazda turgani yaxshi

**Comment by ShokhrukhTurgunov** [comment]
ha to'g'ri, bunga e'tibor bermagan ekanman. maketda adashgan shekilli(hazil). Lekin hozir holati yaxshiga o'xshadi.
