### ISSUE TITLE
border of shoping-bag

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/classic#5]
maketda shopping bag hover bo'lganda border yo'q
![image](https://user-images.githubusercontent.com/79502241/116643522-af814e00-a98a-11eb-9457-c0219a2afa75.png)

sizda boder ko'rinyapti
![image](https://user-images.githubusercontent.com/79502241/116643635-ebb4ae80-a98a-11eb-8fe2-e0592543170a.png)

**Comment by ShokhrukhTurgunov** [comment]
rahmat, e'tibor bermagan ekanman. to'g'rilab qo'ydim
