### ISSUE TITLE
labels for inputs

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/classic#6]
![image](https://user-images.githubusercontent.com/79502241/116644402-ae512080-a98c-11eb-91b9-201439e63177.png)
menimcha ikkta ketma-ket label emas balki birinchi label va unga qarashli input keyin ikkinchi label va inkkinchi input

**Comment by ShokhrukhTurgunov** [comment]
ha shunaqa ekan, to'g'riladim.
