### ISSUE TITLE
backgroundga rasm yo'nalishini ko'rsatish

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/classic#7]
![image](https://user-images.githubusercontent.com/79502241/116645018-55828780-a98e-11eb-8d42-8a269fa688d8.png)
backgroundga rasm yo'nalishini ko'rsatganda "" bular ichida yozilgani yaxshi Muhammadjavohir aka shunday deganini eshitgandim

**Comment by ShokhrukhTurgunov** [comment]
ha shunaqa ekan, pastdagi backgroundlarni shunaqa qilib ketdim
