### ISSUE TITLE
umumiy stylelarni bitta umumiy classda berish

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/classic#8]
![image](https://user-images.githubusercontent.com/79502241/116645261-da6da100-a98e-11eb-92df-e007a0a0adf8.png)
bu yerda `.formadjio-pizza::before` uchun ham bu `.kvatro-formadjio::before` uchun ham va boshqa pizza elemtlar uchun ham  umumiy stylelar mavjud umumiy stylelarni bitta classga olib qolganlarnini alohida berilshi yaxshi bu cod takrorlanishini va hajmini kamayishiga sabab bo'ladi ya'ni:
![image](https://user-images.githubusercontent.com/79502241/116645708-cb3b2300-a98f-11eb-838b-ff3963297f9f.png)
bu kabi

**Comment by ShokhrukhTurgunov** [comment]
rahmat, shunday qildim. kodim ancha qisqardi. hayolga kelmabti
