### ISSUE TITLE
selectorlarni kamaytirish 

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/classic#9]
yuqoridagi issuega amal qilinsa selectorlar soni sezilarni kamayadi yani bitta umumiy class orqali barcha pizza elementlarini tanlash mumkin
![image](https://user-images.githubusercontent.com/79502241/116645869-2836d900-a990-11eb-9392-6cac386ed5ef.png)

**Comment by ShokhrukhTurgunov** [comment]
ha bundan oldingi aytganingiz bo'yicha buni ham to'g'riladim
